/**
 * Machine-readable error code constants.
 *
 * Use these when constructing TalonError subclass instances so that callers
 * can identify failure reasons without parsing message strings.
 *
 * @example
 * ```ts
 * throw new ConfigError('config file missing', undefined);
 * // or: new ConfigError(ErrorCodes.CONFIG_NOT_FOUND)
 * ```
 */
export const ErrorCodes = {
  // Config
  CONFIG_NOT_FOUND: 'CONFIG_NOT_FOUND',
  CONFIG_INVALID: 'CONFIG_INVALID',
  CONFIG_MISSING_FIELD: 'CONFIG_MISSING_FIELD',

  // Database
  DB_CONNECTION_FAILED: 'DB_CONNECTION_FAILED',
  DB_QUERY_FAILED: 'DB_QUERY_FAILED',
  DB_MIGRATION_FAILED: 'DB_MIGRATION_FAILED',
  DB_CONSTRAINT_VIOLATION: 'DB_CONSTRAINT_VIOLATION',

  // IPC
  IPC_WRITE_FAILED: 'IPC_WRITE_FAILED',
  IPC_READ_FAILED: 'IPC_READ_FAILED',
  IPC_VALIDATION_FAILED: 'IPC_VALIDATION_FAILED',
  IPC_TIMEOUT: 'IPC_TIMEOUT',

  // Sandbox
  SANDBOX_SPAWN_FAILED: 'SANDBOX_SPAWN_FAILED',
  SANDBOX_NOT_FOUND: 'SANDBOX_NOT_FOUND',
  SANDBOX_TIMEOUT: 'SANDBOX_TIMEOUT',
  SANDBOX_CRASHED: 'SANDBOX_CRASHED',

  // Tools
  TOOL_NOT_FOUND: 'TOOL_NOT_FOUND',
  TOOL_DENIED: 'TOOL_DENIED',
  TOOL_EXECUTION_FAILED: 'TOOL_EXECUTION_FAILED',
  TOOL_TIMEOUT: 'TOOL_TIMEOUT',

  // Channel
  CHANNEL_SEND_FAILED: 'CHANNEL_SEND_FAILED',
  CHANNEL_CONNECT_FAILED: 'CHANNEL_CONNECT_FAILED',
  CHANNEL_NOT_FOUND: 'CHANNEL_NOT_FOUND',

  // Queue
  QUEUE_ENQUEUE_FAILED: 'QUEUE_ENQUEUE_FAILED',
  QUEUE_DEAD_LETTER: 'QUEUE_DEAD_LETTER',

  // Schedule
  SCHEDULE_INVALID_EXPRESSION: 'SCHEDULE_INVALID_EXPRESSION',

  // Policy
  POLICY_CAPABILITY_DENIED: 'POLICY_CAPABILITY_DENIED',
  POLICY_APPROVAL_TIMEOUT: 'POLICY_APPROVAL_TIMEOUT',
  POLICY_APPROVAL_DENIED: 'POLICY_APPROVAL_DENIED',

  // Memory
  MEMORY_WRITE_DENIED: 'MEMORY_WRITE_DENIED',

  // Persona
  PERSONA_NOT_FOUND: 'PERSONA_NOT_FOUND',
  PERSONA_INVALID: 'PERSONA_INVALID',
} as const;

/** Union of all known error code string values. */
export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
